version: '3.8'

services:
  airspace-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airspace-challenge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - data-loader
    env_file:
      - .env
    networks:
      - airspace
    restart: always

  # uncomment volumes in postgres and run with data-loader
  # service once then comment out data-loader if you want to persist postgres data.
  # TODO: Load data with class.
  data-loader:
    build:
      context: cmd/data-loader/.
      dockerfile: Dockerfile
    container_name: data-loader
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - airspace
    restart: no

  postgres:
    hostname: postgres
    build:
      context: infra/postgres/.
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - airspace
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      # uncomment if you want to persist the data to volume.
#    volumes:
#      - airspace-data:/var/lib/postgresql/data

networks:
  airspace:
    driver: bridge

volumes:
  airspace-data:
