version: '3.8'

services:
  airspace-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airspace-challenge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - data-loader
    env_file:
      - .env
    networks:
      - airspace
    restart: always

  data-loader:
    build:
      context: cmd/data-loader/.
      dockerfile: Dockerfile
    container_name: data-loader
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - airspace
    restart: no

  postgres:
    hostname: postgres
    build:
      context: infra/postgres/.
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - airspace
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks:
  airspace:
    driver: bridge

volumes:
  airspace-data: